### ISSUE TITLE
Unused arguments

### ISSUE THREAD

**Issue by EdwardBerman** [mcclearyj/cweb_psf#8]
In line 119 of src/psfmaker.py, psm_im is instantiated with _make_single_, supplying arguments for x and y with x_pos = x , y_pos = y. x_pos and y_pos are arguments for _make_single, however, x_pos and y_pos are not used within the _make_single_ function itself so I'm not sure why they are arguments. In _make_pexim _make_piff_, x_pos and y_pos are used to specify the location of the psf model, so my main concern would be that _make_single_ is supposed to make webb psfs that very across the field of view, but is instead displaying the same webb PSF for each (x,y) pair. If this is the case, a fix might be adding an nc.detector_position somewhere. If this is not the case, I think that the x_pos y_pos may be removed as arguments in line 271 and in line 119. In render_psf, the x and y arguments would be optional depending on the psf type.

**Comment by mcclearyj** [comment]
Fixed when psfmaker was replaced with get_galaxy_cutouts
